create table
  public.day (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    day_name text null default ''::text,
    diary_id bigint null,
    constraint Day_pkey primary key (id),
    constraint day_diary_id_fkey foreign key (diary_id) references diary (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
  public.diary (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    constraint Diary_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.entry (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    day_id bigint null,
    reps integer null,
    goal_reps integer null,
    weight integer null,
    goal_weight integer null,
    comments text null,
    exercise_id bigint null,
    constraint Entry_pkey primary key (id),
    constraint entry_day_id_fkey foreign key (day_id) references day (id) on update cascade on delete cascade,
    constraint entry_exercise_id_fkey foreign key (exercise_id) references exercise (id)
  ) tablespace pg_default;

create table
  public.exercise (
    id bigint generated by default as identity,
    name text not null default ''::text,
    description text null,
    body_part text null,
    constraint Exercise_pkey primary key (id)
  ) tablespace pg_default;

/* exercises */
insert into
  "exercise" (name, description, body_part)
values
  (
    'Bench Press',
    'lying on a bench and pressing weight upward using either a barbell or a pair of dumbbells',
    'Chest'
  )

insert into
  "exercise" (name, description, body_part)
values
  (
    'Squat',
    'Keeping your back straight and your head up,
bend at your knees without your knees passing your toes, 
sticking out your butt until your legs bend at 90 degrees. Then straighten back up following the same rules in reverse.',
    'Glutes / Legs'
  )

/* flow 2 */
insert into
  "diary" (id)
values
  (
    11
  )

/* flow 3 */
insert into
  "diary" (id)
values
  (
    13
  )
;

COMMIT;

insert into
  "day" (id, day_name, diary_id)
values
  (
    1, 'Tuesday', 13
  )
;

insert into
  "day" (day_name, diary_id)
values
  (
    'Wednesday', 13
  )
;

insert into
  "day" (day_name, diary_id)
values
  (
    'Thursday', 13
  )
;

insert into
  "day" (day_name, diary_id)
values
  (
    'Saturday', 13
  )
;

COMMIT;

insert into
  "entry" (day_id, goal_reps, goal_weight, exercise_id)
values
  (
    1, 10, 225, 3
  )
;