create table
  public.diary (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    owner text not null,
    constraint Diary_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.day (
    id bigint generated by default as identity,
    day_name text not null default ''::text,
    diary_id bigint not null,
    constraint Day_pkey primary key (id),
    constraint day_diary_id_fkey foreign key (diary_id) references diary (id) on update cascade on delete cascade
  ) tablespace pg_default;

create table
public.exercise (
  name text not null,
  rating real null,
  instructions text[] null default '{}'::text[],
  type text null default ''::text,
  muscle text null default ''::text,
  equipment text null default ''::text,
  level text null default ''::text,
  constraint exercise_pkey primary key (name)
) tablespace pg_default;

create table
  public.entry (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    day_id bigint null,
    exercise text not null,
    reps integer null,
    goal_reps integer not null,
    weight integer null,
    goal_weight integer not null,
    comments text null default ''::text,
    last_updated timestamp with time zone null,
    constraint Entry_pkey primary key (id),
    constraint entry_day_id_fkey foreign key (day_id) references day (id) on update cascade on delete cascade,
    constraint entry_exercise_fkey foreign key (exercise) references exercise (name) on update cascade on delete cascade
  ) tablespace pg_default;

COPY exercise FROM '\ExerciseDiary\exercise_rows.csv' WITH CSV HEADER;